### ISSUE TITLE
Build failed in archlinux latest version

### ISSUE THREAD

**Issue by sep2** [microsoft/ClangSharp#201]
branch: master
commit: 0931f42484a8295722e9d2de6f1337557bf286ec

command:
```
git clone https://github.com/microsoft/ClangSharp.git
cd ClangSharp/
./scripts/cibuild.sh
```

Total tests: 390
     Passed: 1
     Failed: 389

All the tests produce same error:
```
   System.DllNotFoundException : Unable to load shared library 'libClangSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibClangSharp: cannot open shared object file: No such file or directory
  Stack Trace:
     at ClangSharp.Interop.clangsharp.Cursor_getDeclKind(CXCursor C)
   at ClangSharp.Interop.CXCursor.get_DeclKind() in /home/user/GitRepos/ClangSharp/sources/ClangSharp/Interop.Extensions/CXCursor.cs:line 524
   at ClangSharp.Decl.Create(CXCursor handle) in /home/user/GitRepos/ClangSharp/sources/ClangSharp/Cursors/Decls/Decl.cs:line 98
   at ClangSharp.Cursor.Create(CXCursor handle) in /home/user/GitRepos/ClangSharp/sources/ClangSharp/Cursors/Cursor.cs:line 64
   at ClangSharp.TranslationUnit.GetOrCreate[TCursor](CXCursor handle) in /home/user/GitRepos/ClangSharp/sources/ClangSharp/TranslationUnit.cs:line 106
   at ClangSharp.TranslationUnit.<.ctor>b__6_0() in /home/user/GitRepos/ClangSharp/sources/ClangSharp/TranslationUnit.cs:line 27
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at ClangSharp.TranslationUnit.get_TranslationUnitDecl() in /home/user/GitRepos/ClangSharp/sources/ClangSharp/TranslationUnit.cs:line 37
   at ClangSharp.PInvokeGenerator.GenerateBindings(TranslationUnit translationUnit, String filePath, String[] clangCommandLineArgs, CXTranslationUnit_Flags translationFlags) in /home/user/GitRepos/ClangSharp/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 248
   at ClangSharp.UnitTests.PInvokeGeneratorTest.ValidateGeneratedBindingsAsync(String inputContents, String expectedOutputContents, PInvokeGeneratorConfigurationOptions configOptions, String[] excludedNames, IReadOnlyDictionary`2 remappedNames, IReadOnlyDictionary`2 withAttributes, IReadOnlyDictionary`2 withCallConvs, IReadOnlyDictionary`2 withLibraryPaths, String[] withSetLastErrors, IReadOnlyDictionary`2 withTypes, IReadOnlyDictionary`2 withUsings, IEnumerable`1 expectedDiagnostics, String libraryPath, String[] commandlineArgs) in /home/user/GitRepos/ClangSharp/tests/ClangSharp.PInvokeGenerator.UnitTests/PInvokeGeneratorTest.cs:line 48
   at ClangSharp.UnitTests.StructDeclarationTest.RemapTest() in /home/user/GitRepos/ClangSharp/tests/ClangSharp.PInvokeGenerator.UnitTests/StructDeclarationTest.cs:line 1808
```

**Comment by tannergooding** [comment]
There isn't currently a build of `libClangSharp` for arch linux. You would need to build it locally or manually copy the binaries for a different Linux Distro and determine if they are compatible.

**Comment by tannergooding** [comment]
https://github.com/microsoft/ClangSharp#building-native provides basic instructions for how to build libClangSharp. This will be required to consume ClangSharp from other Linux platforms.
